import { Pagination } from "@/components/layout/Pagination";
import { ProductBox } from "@/components/layout/ProductBox";
import { Tabs } from "@/components/layout/Tabs";
import { Wrapper } from "@/components/styled/wrapper";
import { useProductsQuery } from "@/hooks/useProductsQuery";
import Head from "next/head";
import { useState } from "react";

const PRODUCTS_PER_PAGE = 12;

export default function Home() {
  const [page, setPage] = useState(1);
  const [tab, setTab] = useState("all");

  const { data, totalProducts } = useProductsQuery({
    page,
    perPage: PRODUCTS_PER_PAGE,
    category: tab,
  });

  const products = data
    ? data.map((product) => <ProductBox key={product.id} {...product} />)
    : null;

  return (
    <>
      <Head>
        <title>uzumaki.drops</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wrapper>
          <div className="tabs-pagination-container">
            <Tabs
              onChange={(tab) => {
                setPage(1);
                setTab(tab);
              }}
              renderRight={
                <Pagination
                  onChange={setPage}
                  page={page}
                  totalPages={Math.floor(totalProducts / PRODUCTS_PER_PAGE)}
                />
              }
            >
              <div tab-value="all">{products}</div>
              <div tab-value="t-shirts">{products}</div>
              <div tab-value="mugs">{products}</div>
            </Tabs>
          </div>
        </Wrapper>
      </main>
    </>
  );
}
